package kkaylium.mods.TechliumCraft.armor;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGlowArmor extends ModelBiped
{
  //fields
    ModelRenderer hoodRight1;
    ModelRenderer hoodRight2;
    ModelRenderer hoodRight3;
    ModelRenderer hoodRight4;
    ModelRenderer hoodLeft1;
    ModelRenderer hoodLeft2;
    ModelRenderer hoodLeft3;
    ModelRenderer hoodLeft4;
    ModelRenderer hoodTop1;
    ModelRenderer hoodBottom3;
    ModelRenderer hoodBottom2;
    ModelRenderer hoodBottom1;
    ModelRenderer hoodBack1;
    ModelRenderer ChestplateFront1;
    ModelRenderer ChestplateFront2;
    ModelRenderer ChestplateFront3;
    ModelRenderer ChestplateFront4;
    ModelRenderer ChestplateFront5;
    ModelRenderer ChestplateFront6;
    ModelRenderer ChestplateLeft1;
    ModelRenderer ChestplateLeft2;
    ModelRenderer ChestplateLeft3;
    ModelRenderer ChestplateLeft4;
    ModelRenderer ChestplateRight1;
    ModelRenderer ChestplateRight2;
    ModelRenderer ChestplateRight3;
    ModelRenderer ChestplateRight4;
    ModelRenderer ChestplateBack1;
    ModelRenderer ChestplateBack2;
    ModelRenderer ChestplateBack3;
    ModelRenderer LeggingFront1;
    ModelRenderer LeggingLeft1;
    ModelRenderer LeggingLeft2;
    ModelRenderer LeggingRight1;
    ModelRenderer LeggingRight2;
    ModelRenderer LeggingBack1;
    ModelRenderer LBootFront1;
    ModelRenderer LBootLeft1;
    ModelRenderer LBootRight1;
    ModelRenderer LBootBack1;
    ModelRenderer LBootRim;
    ModelRenderer RBootFront1;
    ModelRenderer RBootLeft1;
    ModelRenderer RBootRight1;
    ModelRenderer RBootBack1;
    ModelRenderer RBootRim;
  
  public ModelGlowArmor(float scale){

    super(scale, 0.0F, 64, 64);
    textureWidth = 256;
    textureHeight = 64;

      hoodRight1 = new ModelRenderer(this, 236, 11);
      hoodRight1.addBox(0F, -4F, -4.5F, 1, 8, 9);
      hoodRight1.setRotationPoint(-5F, -4F, -0.5F);
      hoodRight1.setTextureSize(256, 64);
      hoodRight1.mirror = true;
      setRotation(hoodRight1, 0F, 0F, 0F);
      hoodRight2 = new ModelRenderer(this, 242, 29);
      hoodRight2.addBox(0F, 0F, -3F, 1, 1, 6);
      hoodRight2.setRotationPoint(-6F, -1F, 0F);
      hoodRight2.setTextureSize(256, 64);
      hoodRight2.mirror = true;
      setRotation(hoodRight2, 0F, 0F, 0F);
      hoodRight3 = new ModelRenderer(this, 252, 48);
      hoodRight3.addBox(0F, 0F, 0F, 1, 1, 1);
      hoodRight3.setRotationPoint(-6F, 0F, -3F);
      hoodRight3.setTextureSize(256, 64);
      hoodRight3.mirror = true;
      setRotation(hoodRight3, 0F, 0F, 0F);
      hoodRight4 = new ModelRenderer(this, 252, 48);
      hoodRight4.addBox(0F, 0F, 0F, 1, 1, 1);
      hoodRight4.setRotationPoint(-6F, 0F, 2F);
      hoodRight4.setTextureSize(256, 64);
      hoodRight4.mirror = true;
      setRotation(hoodRight4, 0F, 0F, 0F);
      hoodLeft1 = new ModelRenderer(this, 236, 11);
      hoodLeft1.addBox(0F, -4F, -4.5F, 1, 8, 9);
      hoodLeft1.setRotationPoint(4F, -4F, -0.5F);
      hoodLeft1.setTextureSize(256, 64);
      hoodLeft1.mirror = true;
      setRotation(hoodLeft1, 0F, 0F, 0F);
      hoodLeft2 = new ModelRenderer(this, 242, 29);
      hoodLeft2.addBox(0F, 0F, -3F, 1, 1, 6);
      hoodLeft2.setRotationPoint(5F, -1F, 0F);
      hoodLeft2.setTextureSize(256, 64);
      hoodLeft2.mirror = true;
      setRotation(hoodLeft2, 0F, 0F, 0F);
      hoodLeft3 = new ModelRenderer(this, 252, 48);
      hoodLeft3.addBox(0F, 0F, 0F, 1, 1, 1);
      hoodLeft3.setRotationPoint(5F, 0F, -3F);
      hoodLeft3.setTextureSize(256, 64);
      hoodLeft3.mirror = true;
      setRotation(hoodLeft3, 0F, 0F, 0F);
      hoodLeft4 = new ModelRenderer(this, 252, 48);
      hoodLeft4.addBox(0F, 0F, 0F, 1, 1, 1);
      hoodLeft4.setRotationPoint(5F, 0F, 2F);
      hoodLeft4.setTextureSize(256, 64);
      hoodLeft4.mirror = true;
      setRotation(hoodLeft4, 0F, 0F, 0F);
      hoodTop1 = new ModelRenderer(this, 222, 0);
      hoodTop1.addBox(-4F, 0F, -4.5F, 8, 1, 9);
      hoodTop1.setRotationPoint(0F, -9F, -0.5F);
      hoodTop1.setTextureSize(256, 64);
      hoodTop1.mirror = true;
      setRotation(hoodTop1, 0F, 0F, 0F);
      hoodBottom3 = new ModelRenderer(this, 246, 51);
      hoodBottom3.addBox(-1F, 0F, -1.5F, 2, 1, 3);
      hoodBottom3.setRotationPoint(4F, 0F, -3.5F);
      hoodBottom3.setTextureSize(256, 64);
      hoodBottom3.mirror = true;
      setRotation(hoodBottom3, 0F, 0F, 0F);
      hoodBottom2 = new ModelRenderer(this, 246, 51);
      hoodBottom2.addBox(-1F, 0F, -1.5F, 2, 1, 3);
      hoodBottom2.setRotationPoint(-4F, 0F, -3.5F);
      hoodBottom2.setTextureSize(256, 64);
      hoodBottom2.mirror = true;
      setRotation(hoodBottom2, 0F, 0F, 0F);
      hoodBottom1 = new ModelRenderer(this, 232, 56);
      hoodBottom1.addBox(-5F, 0F, -1F, 10, 1, 2);
      hoodBottom1.setRotationPoint(0F, 0F, 3F);
      hoodBottom1.setTextureSize(256, 64);
      hoodBottom1.mirror = true;
      setRotation(hoodBottom1, 0F, 0F, 0F);
      hoodBack1 = new ModelRenderer(this, 238, 38);
      hoodBack1.addBox(-4F, -4F, 0F, 8, 8, 1);
      hoodBack1.setRotationPoint(0F, -4F, 4F);
      hoodBack1.setTextureSize(256, 64);
      hoodBack1.mirror = true;
      setRotation(hoodBack1, 0F, 0F, 0F);
      ChestplateFront1 = new ModelRenderer(this, 207, 0);
      ChestplateFront1.addBox(-3F, -4F, 0F, 6, 8, 1);
      ChestplateFront1.setRotationPoint(0F, 6F, -3F);
      ChestplateFront1.setTextureSize(256, 64);
      ChestplateFront1.mirror = true;
      setRotation(ChestplateFront1, 0F, 0F, 0F);
      ChestplateFront2 = new ModelRenderer(this, 231, 11);
      ChestplateFront2.addBox(0F, -1F, 0F, 1, 2, 1);
      ChestplateFront2.setRotationPoint(-3F, 1F, -3F);
      ChestplateFront2.setTextureSize(256, 64);
      ChestplateFront2.mirror = true;
      setRotation(ChestplateFront2, 0F, 0F, 0F);
      ChestplateFront3 = new ModelRenderer(this, 231, 11);
      ChestplateFront3.addBox(0F, -1F, 0F, 1, 2, 1);
      ChestplateFront3.setRotationPoint(2F, 1F, -3F);
      ChestplateFront3.setTextureSize(256, 64);
      ChestplateFront3.mirror = true;
      setRotation(ChestplateFront3, 0F, 0F, 0F);
      ChestplateFront4 = new ModelRenderer(this, 231, 11);
      ChestplateFront4.addBox(0F, 0F, 0F, 1, 1, 1);
      ChestplateFront4.setRotationPoint(1F, 1F, -3F);
      ChestplateFront4.setTextureSize(256, 64);
      ChestplateFront4.mirror = true;
      setRotation(ChestplateFront4, 0F, 0F, 0F);
      ChestplateFront5 = new ModelRenderer(this, 231, 11);
      ChestplateFront5.addBox(0F, 0F, 0F, 1, 1, 1);
      ChestplateFront5.setRotationPoint(-2F, 1F, -3F);
      ChestplateFront5.setTextureSize(256, 64);
      ChestplateFront5.mirror = true;
      setRotation(ChestplateFront5, 0F, 0F, 0F);
      ChestplateFront6 = new ModelRenderer(this, 225, 15);
      ChestplateFront6.addBox(-2F, -2F, 0F, 4, 4, 1);
      ChestplateFront6.setRotationPoint(0F, 5F, -4F);
      ChestplateFront6.setTextureSize(256, 64);
      ChestplateFront6.mirror = true;
      setRotation(ChestplateFront6, 0F, 0F, -0.7807508F);
      ChestplateLeft1 = new ModelRenderer(this, 224, 11);
      ChestplateLeft1.addBox(-1F, 0F, 0F, 2, 1, 1);
      ChestplateLeft1.setRotationPoint(4F, 8F, -3F);
      ChestplateLeft1.setTextureSize(256, 64);
      ChestplateLeft1.mirror = true;
      setRotation(ChestplateLeft1, 0F, 0F, 0F);
      ChestplateLeft2 = new ModelRenderer(this, 224, 11);
      ChestplateLeft2.addBox(0F, 0F, 0F, 2, 1, 1);
      ChestplateLeft2.setRotationPoint(3F, 4F, -3F);
      ChestplateLeft2.setTextureSize(256, 64);
      ChestplateLeft2.mirror = true;
      setRotation(ChestplateLeft2, 0F, 0F, 0F);
      ChestplateLeft3 = new ModelRenderer(this, 225, 21);
      ChestplateLeft3.addBox(0F, 0F, -2F, 1, 1, 4);
      ChestplateLeft3.setRotationPoint(4F, 8F, 0F);
      ChestplateLeft3.setTextureSize(256, 64);
      ChestplateLeft3.mirror = true;
      setRotation(ChestplateLeft3, 0F, 0F, 0F);
      ChestplateLeft4 = new ModelRenderer(this, 225, 21);
      ChestplateLeft4.addBox(0F, 0F, -2F, 1, 1, 4);
      ChestplateLeft4.setRotationPoint(4F, 4F, 0F);
      ChestplateLeft4.setTextureSize(256, 64);
      ChestplateLeft4.mirror = true;
      setRotation(ChestplateLeft4, 0F, 0F, 0F);
      ChestplateRight1 = new ModelRenderer(this, 224, 11);
      ChestplateRight1.addBox(-1F, 0F, 0F, 2, 1, 1);
      ChestplateRight1.setRotationPoint(-4F, 8F, -3F);
      ChestplateRight1.setTextureSize(256, 64);
      ChestplateRight1.mirror = true;
      setRotation(ChestplateRight1, 0F, 0F, 0F);
      ChestplateRight2 = new ModelRenderer(this, 224, 11);
      ChestplateRight2.addBox(-1F, 0F, 0F, 2, 1, 1);
      ChestplateRight2.setRotationPoint(-4F, 4F, -3F);
      ChestplateRight2.setTextureSize(256, 64);
      ChestplateRight2.mirror = true;
      setRotation(ChestplateRight2, 0F, 0F, 0F);
      ChestplateRight3 = new ModelRenderer(this, 225, 21);
      ChestplateRight3.addBox(0F, 0F, -2F, 1, 1, 4);
      ChestplateRight3.setRotationPoint(-5F, 8F, 0F);
      ChestplateRight3.setTextureSize(256, 64);
      ChestplateRight3.mirror = true;
      setRotation(ChestplateRight3, 0F, 0F, 0F);
      ChestplateRight4 = new ModelRenderer(this, 225, 21);
      ChestplateRight4.addBox(0F, 0F, -2F, 1, 1, 4);
      ChestplateRight4.setRotationPoint(-5F, 4F, 0F);
      ChestplateRight4.setTextureSize(256, 64);
      ChestplateRight4.mirror = true;
      setRotation(ChestplateRight4, 0F, 0F, 0F);
      ChestplateBack1 = new ModelRenderer(this, 213, 27);
      ChestplateBack1.addBox(-5F, 0F, 0F, 10, 1, 1);
      ChestplateBack1.setRotationPoint(0F, 8F, 2F);
      ChestplateBack1.setTextureSize(256, 64);
      ChestplateBack1.mirror = true;
      setRotation(ChestplateBack1, 0F, 0F, 0F);
      ChestplateBack2 = new ModelRenderer(this, 213, 27);
      ChestplateBack2.addBox(-5F, 0F, 0F, 10, 1, 1);
      ChestplateBack2.setRotationPoint(0F, 4F, 2F);
      ChestplateBack2.setTextureSize(256, 64);
      ChestplateBack2.mirror = true;
      setRotation(ChestplateBack2, 0F, 0F, 0F);
      ChestplateBack3 = new ModelRenderer(this, 213, 30);
      ChestplateBack3.addBox(-5F, 0F, 0F, 10, 23, 1);
      ChestplateBack3.setRotationPoint(0F, 1F, 2F);
      ChestplateBack3.setTextureSize(256, 64);
      ChestplateBack3.mirror = true;
      setRotation(ChestplateBack3, 0.1487144F, 0F, 0F);
      LeggingFront1 = new ModelRenderer(this, 184, 0);
      LeggingFront1.addBox(-5F, -1.5F, 0F, 10, 2, 1);
      LeggingFront1.setRotationPoint(0F, 11.5F, -3F);
      LeggingFront1.setTextureSize(256, 64);
      LeggingFront1.mirror = true;
      setRotation(LeggingFront1, 0F, 0F, 0F);
      LeggingLeft1 = new ModelRenderer(this, 196, 5);
      LeggingLeft1.addBox(0F, -1.5F, -2F, 1, 2, 4);
      LeggingLeft1.setRotationPoint(4F, 11.5F, 0F);
      LeggingLeft1.setTextureSize(256, 64);
      LeggingLeft1.mirror = true;
      setRotation(LeggingLeft1, 0F, 0F, 0F);
      LeggingLeft2 = new ModelRenderer(this, 202, 13);
      LeggingLeft2.addBox(0F, 0F, 0F, 1, 8, 1);
      LeggingLeft2.setRotationPoint(4F, 12F, -1F);
      LeggingLeft2.setTextureSize(256, 64);
      LeggingLeft2.mirror = true;
      setRotation(LeggingLeft2, 0F, 0F, 0F);
      LeggingRight1 = new ModelRenderer(this, 196, 5);
      LeggingRight1.addBox(0F, -1.5F, -2F, 1, 2, 4);
      LeggingRight1.setRotationPoint(-5F, 11.5F, 0F);
      LeggingRight1.setTextureSize(256, 64);
      LeggingRight1.mirror = true;
      setRotation(LeggingRight1, 0F, 0F, 0F);
      LeggingRight2 = new ModelRenderer(this, 202, 13);
      LeggingRight2.addBox(-1F, 0F, 0F, 1, 8, 1);
      LeggingRight2.setRotationPoint(-4F, 12F, -1F);
      LeggingRight2.setTextureSize(256, 64);
      LeggingRight2.mirror = true;
      setRotation(LeggingRight2, 0F, 0F, 0F);
      LeggingBack1 = new ModelRenderer(this, 184, 0);
      LeggingBack1.addBox(-5F, -1.5F, 0F, 10, 2, 1);
      LeggingBack1.setRotationPoint(0F, 11.5F, 2F);
      LeggingBack1.setTextureSize(256, 64);
      LeggingBack1.mirror = true;
      setRotation(LeggingBack1, 0F, 0F, 0F);
      LBootFront1 = new ModelRenderer(this, 171, 0);
      LBootFront1.addBox(-2F, 0F, 0F, 4, 2, 1);
      LBootFront1.setRotationPoint(2F, 22F, -3F);
      LBootFront1.setTextureSize(256, 64);
      LBootFront1.mirror = true;
      setRotation(LBootFront1, 0F, 0F, 0F);
      LBootLeft1 = new ModelRenderer(this, 171, 5);
      LBootLeft1.addBox(0F, 0F, -2F, 1, 2, 4);
      LBootLeft1.setRotationPoint(4F, 22F, 0F);
      LBootLeft1.setTextureSize(256, 64);
      LBootLeft1.mirror = true;
      setRotation(LBootLeft1, 0F, 0F, 0F);
      LBootRight1 = new ModelRenderer(this, 171, 5);
      LBootRight1.addBox(0F, 0F, -2F, 1, 3, 4);
      LBootRight1.setRotationPoint(0F, 21F, 0F);
      LBootRight1.setTextureSize(256, 64);
      LBootRight1.mirror = true;
      setRotation(LBootRight1, 0F, 0F, 0F);
      LBootBack1 = new ModelRenderer(this, 171, 13);
      LBootBack1.addBox(-2F, 0F, 0F, 4, 2, 1);
      LBootBack1.setRotationPoint(2F, 22F, 2F);
      LBootBack1.setTextureSize(256, 64);
      LBootBack1.mirror = true;
      setRotation(LBootBack1, 0F, 0F, 0F);
      LBootRim = new ModelRenderer(this, 157, 18);
      LBootRim.addBox(-3F, 0F, -3F, 6, 2, 6);
      LBootRim.setRotationPoint(2F, 20F, 0F);
      LBootRim.setTextureSize(256, 64);
      LBootRim.mirror = true;
      setRotation(LBootRim, 0F, 0F, 0F);
      RBootFront1 = new ModelRenderer(this, 171, 0);
      RBootFront1.addBox(-2F, 0F, 0F, 4, 2, 1);
      RBootFront1.setRotationPoint(-2F, 22F, -3F);
      RBootFront1.setTextureSize(256, 64);
      RBootFront1.mirror = true;
      setRotation(RBootFront1, 0F, 0F, 0F);
      RBootLeft1 = new ModelRenderer(this, 171, 5);
      RBootLeft1.addBox(0F, 0F, -2F, 1, 3, 4);
      RBootLeft1.setRotationPoint(-1F, 21F, 0F);
      RBootLeft1.setTextureSize(256, 64);
      RBootLeft1.mirror = true;
      setRotation(RBootLeft1, 0F, 0F, 0F);
      RBootRight1 = new ModelRenderer(this, 171, 5);
      RBootRight1.addBox(0F, 0F, -2F, 1, 2, 4);
      RBootRight1.setRotationPoint(-5F, 22F, 0F);
      RBootRight1.setTextureSize(256, 64);
      RBootRight1.mirror = true;
      setRotation(RBootRight1, 0F, 0F, 0F);
      RBootBack1 = new ModelRenderer(this, 171, 13);
      RBootBack1.addBox(-2F, 0F, 0F, 4, 2, 1);
      RBootBack1.setRotationPoint(-2F, 22F, 2F);
      RBootBack1.setTextureSize(256, 64);
      RBootBack1.mirror = true;
      setRotation(RBootBack1, 0F, 0F, 0F);
      RBootRim = new ModelRenderer(this, 157, 18);
      RBootRim.addBox(-3F, 0F, -3F, 6, 2, 6);
      RBootRim.setRotationPoint(-2F, 20F, 0F);
      RBootRim.setTextureSize(256, 64);
      RBootRim.mirror = true;
      setRotation(RBootRim, 0F, 0F, 0F);

      this.bipedHead.addChild(hoodTop1);
      this.bipedHead.addChild(hoodLeft1);
      this.bipedHead.addChild(hoodLeft2);
      this.bipedHead.addChild(hoodLeft3);
      this.bipedHead.addChild(hoodLeft4);
      this.bipedHead.addChild(hoodRight1);
      this.bipedHead.addChild(hoodRight2);
      this.bipedHead.addChild(hoodRight3);
      this.bipedHead.addChild(hoodRight4);
      this.bipedHead.addChild(hoodBack1);
      this.bipedHead.addChild(hoodBottom1);
      this.bipedHead.addChild(hoodBottom2);
      this.bipedHead.addChild(hoodBottom3);
      this.bipedHead.addChild(hoodBack1);

      this.bipedBody.addChild(ChestplateFront1);
      this.bipedBody.addChild(ChestplateFront2);
      this.bipedBody.addChild(ChestplateFront3);
      this.bipedBody.addChild(ChestplateFront4);
      this.bipedBody.addChild(ChestplateFront5);
      this.bipedBody.addChild(ChestplateFront6);
      this.bipedBody.addChild(ChestplateLeft1);
      this.bipedBody.addChild(ChestplateLeft2);
      this.bipedBody.addChild(ChestplateLeft3);
      this.bipedBody.addChild(ChestplateLeft4);
      this.bipedBody.addChild(ChestplateRight1);
      this.bipedBody.addChild(ChestplateRight2);
      this.bipedBody.addChild(ChestplateRight3);
      this.bipedBody.addChild(ChestplateRight4);
      this.bipedBody.addChild(ChestplateBack1);
      this.bipedBody.addChild(ChestplateBack2);
      this.bipedBody.addChild(ChestplateBack3);

      this.bipedLeftLeg.addChild(LeggingFront1);
      this.bipedLeftLeg.addChild(LeggingBack1);
      this.bipedLeftLeg.addChild(LeggingLeft1);
      this.bipedRightLeg.addChild(LeggingRight1);
      this.bipedLeftLeg.addChild(LeggingLeft2);
      this.bipedRightLeg.addChild(LeggingRight2);

      this.bipedLeftLeg.addChild(LBootFront1);
      this.bipedLeftLeg.addChild(LBootBack1);
      this.bipedLeftLeg.addChild(LBootLeft1);
      this.bipedLeftLeg.addChild(LBootRight1);
      this.bipedLeftLeg.addChild(LBootRim);

      this.bipedRightLeg.addChild(RBootFront1);
      this.bipedRightLeg.addChild(RBootBack1);
      this.bipedRightLeg.addChild(RBootRight1);
      this.bipedRightLeg.addChild(RBootLeft1);
      this.bipedRightLeg.addChild(RBootRim);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
